# Commands to start on workspace startup
tasks:
  - init: npm install
    command: npm run build && npm run start
# Ports to expose on workspace startup
ports:
  - port: 1234
    onOpen: open-preview
