# Commands to start on workspace startup
tasks:
  - name: Install and build
    init: >
      npm install && 
      npm run build &&
      gp sync-done parcel-build

  - name: Parcel watch
    init: gp sync-await parcel-build
    command: npm run watch

  - name: Start server
    init: gp sync-await parcel-build
    command: npm run serve-gitpod
    openMode: split-right
# Ports to expose on workspace startup
ports:
  - port: 3000
    onOpen: open-preview
